char: random: upsteam to v1.41.0
Squashed commit of the following:

commit 7e813f86b7de2895ac6dc9d6912c044187fe6d84
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Thu May 12 17:02:50 2022 +0800

    srandom: enable Ultra High Speed mode

commit 8bb29ac839002b2ef8691bba3df30f176b5ab426
Author: Jonathan Senkerik <josenk@jintegrate.co>
Date:   Thu May 12 16:31:56 2022 +0800

    srandom: v1.41.0, Add Ultra High Speed mode

    https://github.com/josenk/srandom/commit/6145b04518a2e6fb3912d4d77eff9fbc4e300e8c

commit 78dd83e93a2ad8e2262fc2316ad605e09ae7ea23
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Sat Mar 12 12:46:34 2022 +0800

    char: srandom: disable logging

    ref: 2c46f17e31cba28936081430e52b8a736432fea1

commit 378eb288a10860d414f03386496f4b0a7364c75d
Author: Jebaitedneko <16777012+Jebaitedneko@users.noreply.github.com>
Date:   Thu Dec 31 11:00:54 2020 +0300

    ARM64: configs: Disable hw_random

    /dev/{u,s,hw_}random all use srandom now

    Signed-off-by: Jebaitedneko <jebaitedneko@gmail.com>
    Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>
    Change-Id: Id788c59d2fb9da786a2a5bc639010c278de75b35

commit 89563422b5e457aae2afa917f5e5a348383099d5
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Sat Mar 12 12:34:36 2022 +0800

    char: srandom: remove srandom stack guard

commit 76905cb8bd555034bf3b08e3be9fffa6707d7058
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Sat Mar 12 12:33:55 2022 +0800

    char: random: fix unused function error

    ../drivers/char/random.c:1036:16: error: unused function 'extract_crng_user' [-Werror,-Wunused-function]
    static ssize_t extract_crng_user(void __user *buf, size_t nbytes)
                   ^
    1 error generated.

commit c540d03a25ea293bf7a6f59c3922a466240bb775
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Wed Dec 16 17:28:36 2020 +0530

    char: mem: register /dev/hw_random through devmem framework when HW_RANDOM is unset

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

commit ae68271ff6d095d557960fcd034616d07a118cba
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Wed Dec 16 16:52:42 2020 +0530

    char: srandom: switch to kzalloc

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

     Conflicts:
    	drivers/char/srandom/srandom.c

commit d45b506d8d33e2a67e4db5e12e276dbe706efbdb
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Wed Dec 16 03:14:44 2020 +0530

    char: srandom: change TIMESPEC struct variable to tsp

    some focaltech touchscreens also export symbols with ts variable causing linker errors

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

     Conflicts:
    	drivers/char/srandom/srandom.c

commit 1a4d2e9623c7243a37341cb4908dbae53d859985
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Wed May 19 06:22:10 2021 +0530

    char: random: use sdevice_{read,write} for {u}random fops

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

     Conflicts:
    	drivers/char/random.c

commit 8c81475654bbdf619dccefbe40aa05fa4fce5fdd
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Tue Dec 15 20:03:42 2020 +0530

    char: mem: link /dev/{u}random to /dev/srandom

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

commit 048dcd69ebb9b3b0dd58886c127e618ff6d3636f
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Tue Dec 15 20:02:31 2020 +0530

    char: srandom: expose sdevice_{read,write} and sfops for treewide usage

    * de-staticify, externify and move the prototypes to srandom.h
    * constify sfops
    * also export sdevice_read and sdevice_write as symbols

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

     Conflicts:
    	drivers/char/srandom/srandom.c

commit e241de7bc18cc5f605cb11f81a1ed84975ea52f2
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Tue Dec 15 18:03:09 2020 +0530

    char: srandom: use ktime_get_real_ts64 and timespec64

    * these were introduced in v3.17-rc1, so let's use them

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

commit e34c8c067f5a2ee5e65173a1da5780880784c59f
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Tue Dec 15 17:42:52 2020 +0530

    char: srandom: expose new Makefile and Kconfig interfaces

    * deprecated the original Makefile
    * added Kconfig interfaces for selecting CONFIG_SRANDOM

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

commit 481a5fb46277cc0e2577e1d08159d7b2707156d5
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Mon Nov 15 21:21:48 2021 +0530

    char: srandom: add Kconfig interface

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

commit 5ac1d3e7256ce803a5b6442cf3538d2f0be04fcd
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Mon Nov 15 21:19:15 2021 +0530

    char: srandom: rewite Makefile for in-kernel builds

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

commit 71aba9c88c0bd841a7db3784ea225a7f2a6aacd8
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Sat Mar 12 01:12:49 2022 +0800

    drivers: Checkout drivers/char/srandom from https://github.com/josenk/srandom/commits/master

commit ab33db8c61ca1640c8fd10ef386e0f0df3cef23f
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:29 2022 +0800

    Revert "drivers: char: Add snapshot of srandom from josenk/srandom"

    This reverts commit b4aeb07fbe32896cc3b28a8e91e8ac9c5c528eca.

commit 7c8b545f3fd2061ee56d401d58af7921f0266ab4
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:29 2022 +0800

    Revert "char: srandom: Refactor for sanity and consistency"

    This reverts commit b64391ad945bd5b4fd7a42a85bd7db4d08ae7d18.

commit 95abcf7552c3b78fe00af7ba6525f8215ac8217e
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:28 2022 +0800

    Revert "char: srandom: Avoid printk logging in srandom"

    This reverts commit f2a62bbd8f37c662c74201de16c9ea857f1608d2.

commit dc9018eda1bec35f2ec3387639c7c9dcb8903973
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:27 2022 +0800

    Revert "char: srandom: Fix comparison ordering warning"

    This reverts commit 78f16207586f64b52fd8dbeadbc31868f0a49385.

commit fbf099a44dd5daf80cf84843f91649541ec2db4c
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:26 2022 +0800

    Revert "char: srandom: use ktime_get_real_ts64 and timespec64"

    This reverts commit 6236bb98c39fd637f47b4017899e10f4755ae250.

commit 17c64dafdf2b40153053347d16dc98f1a78389eb
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:26 2022 +0800

    Revert "char: srandom: switch to kzalloc"

    This reverts commit 4ec60afc4ddb24e11a847ae7479dd351c121435e.

commit 6bd763cca61fcc3fbb64d9d56772abf9bc436db2
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:25 2022 +0800

    Revert "char: srandom: Expose sdevice_{read,write} and sfops for external usage"

    This reverts commit 0552652713f8c0afcfeb174888abe74ee40905bf.

commit f35bb7fb5a9184e8b7ada3678d98044293d88809
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:24 2022 +0800

    Revert "char: mem: link /dev/{u}random to /dev/srandom"

    This reverts commit 6f5140215d05789443fa119959f79b1733131cc5.

commit 7975b36644d846135500e872aa98396ff1260842
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:54:56 2022 +0800

    Revert "char: srandom: Silence logging"

    This reverts commit ccc0e43aa5616031eb50df2b078b115f2b122895.